# vim: set expandtab shiftwidth=2 tabstop=8 textwidth=0:

include:
  - project: 'freedesktop/ci-templates'
    ref: 59de540b620c45739871d1a073d76d5521989d11 # see https://docs.gitlab.com/ee/ci/yaml/#includefile
    file: '/templates/fedora.yml'


variables:
  FDO_UPSTREAM_REPO: xorg/drivers/xf86-input-emulated


stages:
  - containers
  - build


.fedora:
  variables:
    FDO_DISTRIBUTION_VERSION: 32
    FDO_DISTRIBUTION_PACKAGES: 'git autoconf automake libtool make xorg-x11-server-devel xorg-x11-util-macros'
    FDO_DISTRIBUTION_TAG: '2020-05-19.0'


fedora@container_build:
  extends:
    - .fedora
    - .fdo.container-build@fedora
  stage: containers
  variables:
    GIT_STRATEGY: none


.default_build:
  stage: build
  script:
    - mkdir _builddir _inst
    - pushd _builddir > /dev/null
    - ../autogen.sh --prefix=$(realpath ../_inst) --disable-silent-rules
    - make && make check
    - make install
    - popd > /dev/null
  artifacts:
    name: "automake-logs-$CI_JOB_NAME"
    when: always
    expire_in: 1 week
    paths:
      - _builddir/config.log


fedora:32@default-build:
  extends:
    - .fedora
    - .fdo.distribution-image@fedora
    - .default_build
